  services:
  mysql:
      container_name: mysql-container
      image: mysql
      volumes:
        - /var/lib/mysql
      ports:
        - 3306:3306
      environment:
        MYSQL_DATABASE: store
        MYSAL_ALLOW_EMPTY_PASSWORD: true